# -*- coding: utf-8 -*-

STREET_TYPE_MAP = { 
                # Street
                'st' => 'Street',
                'str' => 'Street',
                'street' => 'Street',
                'qucha' => 'Street',
                'qutsa' => 'Street',
                'quch' => 'Street',
                'qacha' => 'Street',
                'qicha' => 'Street',
                'quca' => 'Street',
                'kucha' => 'Street',
                'kutsa' => 'Street',
                'kuch' => 'Street',
                'kacha' => 'Street',
                'kicha' => 'Street',
                'kuca' => 'Street',
                'k' => 'Street',
                'q' => 'Street',
                'quchaze' => 'Street',
                'qutsaze' => 'Street',
                'quchze' => 'Street',
                'qachaze' => 'Street',
                'qichaze' => 'Street',
                'qucaze' => 'Street',
                'kuchaze' => 'Street',
                'kutsaze' => 'Street',
                'kuchze' => 'Street',
                'kachaze' => 'Street',
                'kichaze' => 'Street',
                'kucaze' => 'Street',
                'k-ze' => 'Street',
                'q-ze' => 'Street',
                # Highway
                'highway' => 'Highway',
                'roadway' => 'Highway',
                'rdwy' => 'Highway',
                'hwy' => 'Highway',
                'gzatketsili' => 'Highway',
                'gzatqetsili' => 'Highway',
                'gzatketzili' => 'Highway',
                'gzatqetzili' => 'Highway',
                # Avenue
                'avenue' => 'Avenue',
                'ave' => 'Avenue',
                'av' => 'Avenue',
                'gamziri' => 'Avenue',
                'gamzir' => 'Avenue',
                'kheivani' => 'Avenue',
                'xeivani' => 'Avenue',
                'khevani' => 'Avenue',
                'xevani' => 'Avenue',
                # Alley
                'alley' => 'Alley',
                'aly' => 'Alley',
                'ally' => 'Alley',
                'aley' => 'Alley',
                'gasasvleli' => 'Alley',
                'gasaxvevi' => 'Alley',
                'gasasveli' => 'Alley',
                'gasakhvevi' => 'Alley',
                'gasakhveli' => 'Alley',
                'gasaxveli' => 'Alley',
                # Rise
                'aghmarti' => 'Rise',
                'agmarti' => 'Rise',
                'rise' => 'Rise',
                # Drive
                'drive' => 'Drive',
                'dr' => 'Drive',
                'chikhi' => 'Drive',
                'chixi' => 'Drive',
                'cixi' => 'Drive',
                'chukhu' => 'Drive',
                # Lane
                'lane' => 'Lane',
                'ln' => 'Lane',
                'lan' => 'Lane',
                'shesakhvevi' => 'Lane',
                'shesaxvevi' => 'Lane',
                # Square
                'square' => 'Square',
                'sq' => 'Square',
                'sqr' => 'Square',
                'moedani' => 'მოედანი',
                'moedan' => 'მოედანი',
                # Bridge
                'bridge' => 'Bridge',
                'brdg' => 'Bridge',
                'br' => 'Bridge',
                'khidi' => 'Bridge',
                'xidi' => 'Bridge'  }

AREA_BUZZ_WORDS = ['region', 'raioni', 'district']
CITY_BUZZ_WORDS = ['city', 'kalaki', 'qalaki', 'qalaqi']