development:
  adapter: mysql2
  encoding: utf8
  database: geocodeAPI_dev
  user: root
  password: qwmlie9!
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: geocodeAPI_prod
  user: root
  password: qwmlie9!
  host: localhost